### ISSUE TITLE
Design record type for spacecraft position and attitude

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn-schema#10]
Design an Avro record schema to model position and attitude of a satellite in low-Earth orbit (i.e., spacecraft state vector). Draw upon FITS headers for housekeeping data used across multiple HEASARC-supported missions.

**Comment by jracusin** [comment]
This probably also needs pointing info.

**Comment by Vidushi-GitHub** [comment]
First part: Design record schema to model position and attitude of a satellite in low-Earth orbit (i.e., spacecraft state vector) has been implemented in [#56.](https://github.com/nasa-gcn/gcn-schema/pull/56)
