### ISSUE TITLE
impossible validation of new schema

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn-schema#117]
I'm trying to design a new set of schema for BurstCube.  Part of the validation script is checking if the id points to a real url as part of the schema browser.  However, since it's a new schema, it doesn't, so it cannot pass validation.

```
✖ node validate.mjs:
error: gcn/notices/burstcube/Alert.example.json: can't resolve reference ../../core/Reporter.schema.json from id https://gcn.nasa.gov/schema/main/gcn/notices/burstcube/alert.schema.json
husky - pre-commit hook exited with code 1 (error)
```

**Comment by dakota002** [comment]
@jracusin do you have a branch with your changes on it so I can examine the issue?

**Comment by jracusin** [comment]
I cannot commit and push my branch because it fails the validation, that's the issue.

**Comment by dakota002** [comment]
You should be able to use the flag `--no-verify` in your commit command to push the code without running checks:

```
git commit -m "..." --no-verify
```

**Comment by jracusin** [comment]
https://github.com/jracusin/gcn-schema/tree/burstcube

**Comment by dakota002** [comment]
Gotcha, I'll take a look

**Comment by dakota002** [comment]
I think you have a mismatch on the paths, 

```
    {
      "$ref": "../core/Alert.schema.json"
    },
    {
      "$ref": "../../core/Reporter.schema.json"
    },
```

The file path `"../core/Alert.schema.json"` is correct, the others with `../../core/etc` need to be changed to `../core/etc`

**Comment by jracusin** [comment]
ok, thanks, so it wasn't the issue I thought.  I see I have other validation issues, and I'll work thru those.  Closing this issue.
