### ISSUE TITLE
schema browser

### ISSUE THREAD

**Issue by Vidushi-GitHub** [nasa-gcn/gcn-schema#121]
@dakota002 somehow one of the core schema, DetectorStatus doesn't appear in [schema browser](https://gcn.nasa.gov/docs/schema/v3.0.0/gcn/notices/core/DetectorStatus.schema.json), please fix it.

We noticed when Judy was presenting BurstCube PR.

**Comment by lpsinger** [comment]
It does appear in the schema browser, but it doesn't have any fields. Indeed, the schema itself defines no fields.

**Comment by Vidushi-GitHub** [comment]
Oh yes, makes sense. Shall we make the on/off/trigger as property?

**Comment by lpsinger** [comment]
This schema defines an enum type but does not define any fields. @dakota002, how should we present this in the schema browser?

**Comment by dakota002** [comment]
Ah i see. Yea the docs page is really blank. I have some ideas, I will play around and upload some screenshots in a bit

**Comment by dakota002** [comment]
@lpsinger @Vidushi-GitHub what are your thoughts on something like this:
![image](https://github.com/nasa-gcn/gcn-schema/assets/11023698/d35cd51c-0ed5-4c9e-a90c-0203d6f79a3b)

**Comment by lpsinger** [comment]
Sure, looks good to me.
