### ISSUE TITLE
Ambiguity with error in core Localization schema

### ISSUE THREAD

**Issue by alchzh** [nasa-gcn/gcn-schema#137]
With the new Localization core schema the error region is defined in the key [`ra_dec_error`](https://github.com/nasa-gcn/gcn-schema/blob/4afa4246f9e584ff9c577ed0ef82118df6fddf13/gcn/notices/core/Localization.schema.json#L16)
 
The term `ra_dec_error` here is confusing for both producers and consumers, since for a circular error region with some error radius in angular separation the declination error is the stated error radius while the right ascension error is actually `≈ error / cos(dec)`.

**Comment by Vidushi-GitHub** [comment]
Description of ra_dec_error is defined clearly as: "An array of up to three values that describe the localization region as an ellipse: length of the semi-major axis, length of the semi-minor axis, and astronomical position angle of the semi-major axis."
It shouldn't create confusion of ra_error definition.

**Comment by lpsinger** [comment]
@alchzh, indeed, we've gone through a few iterations of the naming and definition of this fields. It's called `ra_dec_error` simply because we have a convention that any field's error quantity is placed in a field whose name has the suffix `_error`.
