### ISSUE TITLE
Add trigger ID in EP Notices

### ISSUE THREAD

**Issue by Vidushi-GitHub** [nasa-gcn/gcn-schema#159]
# Current behavior
Following the Zendesk ticket #210 (https://nasa-gcn.zendesk.com/agent/tickets/210):
The same event is being notified through both Notices and Circulars. However, they don't contain a common unique ID and have slightly different times and localization (as Circulars are more refined).

# Expected behavior
Include a property such as the event name or trigger ID as a unique ID, which should be the same across both Notices and Circulars.

Resolves #155 and #160

**Comment by jracusin** [comment]
Waiting on EP team to add event ID from their pipeline to notices and approve new version of schema.

**Comment by modot** [comment]
I'm on it.

**Comment by Vidushi-GitHub** [comment]
Thanks @modot. We found that the EP team is utilizing the new schema version, and the id field is present in EP Notices. 
Just for information, we have announced it to the users as well (see, https://gcn.nasa.gov/news#circulars-are-now-available-via-kafka-heartbeat-kafka-topic-and-schema-release-v410)

**Comment by Vidushi-GitHub** [comment]
This issue has been addressed, hence closing it.
