### ISSUE TITLE
Unified Schema - Avro Vs JSON

### ISSUE THREAD

**Issue by Vidushi-GitHub** [nasa-gcn/gcn-schema#17]
- [x] File formats

    - Input in JSON or Avro or, convert between them?
        - But JSON doesn’t require type/description
        - JSON is very widely used
        - Avro is faster and has better compression - limitation given size of file

    - What will be done with VOEvent?

- [x] Unified schema

    - Which schema registry?
        - access requirements for schema registry web UI
        - approval flow for PRs
        - If not, how do we validate schema?  Don't we?

    - Would we allow submissions outside of unified schema?
        - we can push NASA missions to use it
        - write conversions for other missions?

- [x]  submission

    - NASA IT access + Client ID/token

    - kafka python binding?? - how does this work?
        - other languages?

- [ ] Archive

    - Convert historical archive into unified schema
        - GCN notices
        - catalogs?

    - new events to go into archive using unified schema DB

- [ ] Issue: attachments

    - Swift only mission that has them, archive is incomplete
        - Swift build their own TDRS products archive
        - SwiftTDRSreceiver program moved out of GCN

    - Healpix maps / Light curves / spectra / images / data files
        - URL at live mission archive?
        - attach to messages?
        - URL to somewhere on GCN?

    - Generate healpix map based on circular localization
        - push missions to do it themselves
        - we can do it as a fallback

**Comment by jracusin** [comment]
These are either closed or moved to https://github.com/nasa-gcn/gcn.nasa.gov/milestone/6
