### ISSUE TITLE
Questions on schema:  What to do with parts of schema that aren't needed

### ISSUE THREAD

**Issue by blaufuss** [nasa-gcn/gcn-schema#43]
Putting together a test alert sender that will send IceCube track alerts, and found the schema, now with examples:
https://github.com/nasa-gcn/gcn-schema/tree/main/gcn/notices/icecube/amon
very helpful.

But as a producer of this information, it's not clear that all parts of some of the reused schema core components apply fully to the IceCube alerts.  

For example:  our initial localizations have a direction and circular errors at the 90% and 50% containment.  
While the 'localization' item in the schema is a bit more complex.  I CAN map the circular error onto an ellipse with equal major/minor axes.  Can we include two containment levels?   Right now our example has err50 added to cover this as a specialized field.  That's fine if that's the preferred 

Another is the FAR.  We report a single FAR value in units of [yr^-1], but the Statistics schema is rather more complex.  OK NOT to supply values when reporting?  And we should match the units?  Hz is doable but our FARs are few/year level.?  

Thanks for guidance, will happily help update the icecube schema(s) moving forward.

**Comment by lpsinger** [comment]
Personally I would prefer to stick with SI units, Hz. Floating point numbers have plenty of dynamic range!

**Comment by blaufuss** [comment]
Thanks Leo, will stick with the SI units.  

What's the guidance on supplying all parts of core schema components, for example:
  "discovery_datetime": {
    "trigger_time": "ISO 8601 time here",
    "observation_start": "ISO 8601 time here",
    "observation_stop": "ISO 8601 time here",
    "observation_livetime": 0
}
    
    For us, it's just a single trigger/observation time for one of our alerts.  Is 
"discovery_datetime": {
       "trigger_time": "2023-03-06T10:59:30.41"
 }
    
    or is
"discovery_datetime": {
       "trigger_time": "2023-03-06T10:59:30.41",
       "observation_start": "2023-03-06T10:59:30.41",
       "observation_stop": "2023-03-06T10:59:30.41",
       "observation_livetime": 0
 }
 preferred?

**Comment by lpsinger** [comment]
You just omit the missing fields entirely. JSON Schema permits that as long as you don't mark the field as required.

**Comment by blaufuss** [comment]
Thanks Leo for the clarification.
