### ISSUE TITLE
Freezing Core Schema?

### ISSUE THREAD

**Issue by Tohuvavohu** [nasa-gcn/gcn-schema#52]
When can we expect the core schema to be frozen? 
I see a few open PRs but don't have a good sense of the road map here...
Please let me know how i can assist in anyway.

LVK/RAVEN needs to know the schema of the alerts they will be listening to.
@Vidushi-GitHub @jracusin @dakota002 @lpsinger

**Comment by lpsinger** [comment]
I don't think we are going to freeze anything, but at some point we should start tagging schema versions.

**Comment by Tohuvavohu** [comment]
Ok, well having some clarity on the development roadmap will help, so I can understand when we can deploy the notices and when we can push the RAVEN listener.

**Comment by jracusin** [comment]
I think we can close this now that we've outlined the plan to tag a version next week, and use that for production until a future agreed-upon update.
